// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rumdeqkrtfjxckqgokoy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ1bWRlcWtydGZqeGNrcWdva295Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODM1NDE5ODYsImV4cCI6MjA5OTExNzk4Nn0.M2vV1Qd_NoYT0hKa88tsAPPlnfSzMmQaLWg8cXbUTSs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// SSR-safe: localStorage only exists in the browser. During server-side
// rendering fall back to Supabase's default in-memory storage.
const isBrowser = typeof window !== "undefined";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: isBrowser ? window.localStorage : undefined,
    persistSession: isBrowser,
    autoRefreshToken: isBrowser,
  }
});
